### ISSUE TITLE
Linux 3.6 and bbswitch power on / off issues.

### ISSUE THREAD

**Issue by cybercyst** [Bumblebee-Project/bbswitch#35]
I recently upgraded to linux 3.6 out of the testing repo in ArchLinux and now bbswitch won't power on and off the card.
I've come from a working bumblebee installation on linux 3.5 and seems that maybe something's changed in the acpi setup.

Here's my dmesg: http://pastebin.archlinux.fr/450067

I have nvidia and nouveau blacklisted and all combinations of bbswitch module options yield the same result.

**Comment by postadelmaga** [comment]
I have similar problem on kernel 4.8.11-1 ( I am using Antergos linux, based on Arch ).

I thought the issue was related to `tlp` and `bsswitch`  conflicting and I have disabled the pci management from tlp for the nvidia card but nothing has really changed.

Sometime it works sometime I got the error:
`Refused to change power state, currently in D3`

**Comment by bluca** [comment]
@postadelmaga I would recommend having a look at the following threads:

https://github.com/Bumblebee-Project/Bumblebee/issues/808
https://github.com/Bumblebee-Project/bbswitch/issues/140
https://github.com/Bumblebee-Project/bbswitch/issues/112
