### ISSUE TITLE
bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM (Acer V5-573G)

### ISSUE THREAD

**Issue by Lekensteyn** [Bumblebee-Project/bbswitch#82]
Originally reported on https://github.com/Bumblebee-Project/Bumblebee/issues/460, written here for reference.

---

Hi,

I'm trying to setup Bumblebee on my new Acer Aspire V5-573G (Haswell i5-4200U, Nvidia GT 750M) running Ubuntu 13.04. Whenever I try to launch a program running optirun, I get the error message stated in the title...

<pre>
felix@Felix-Laptop:~$ optirun -vv --debug bash
[  128.536692] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[  128.537077] [INFO]Configured driver: nvidia
[  128.537246] [DEBUG]optirun version 3.2.1 starting...
[  128.537258] [DEBUG]Active configuration:
[  128.537264] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  128.537270] [DEBUG] X display: :8
[  128.537275] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-325:/usr/lib32/nvidia-325
[  128.537281] [DEBUG] Socket path: /var/run/bumblebee.socket
[  128.537286] [DEBUG] Accel/display bridge: auto
[  128.537292] [DEBUG] VGL Compression: proxy
[  128.537297] [DEBUG] VGLrun extra options: 
[  128.537303] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[  128.537364] [DEBUG]Using auto-detected bridge virtualgl
[  128.690221] [INFO]Response: No - error: [XORG] (EE) NVIDIA(0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please

[  128.690240] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) NVIDIA(0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please

[  128.690247] [DEBUG]Socket closed.
[  128.690267] [ERROR]Aborting because fallback start is disabled.
[  128.690273] [DEBUG]Killing all remaining processes.
</pre>

My dmesg log prints some error messages regarding bbswitch:

<pre>
[    2.610668] bbswitch: module verification failed: signature and/or required key missing - tainting kernel
[    2.610827] bbswitch: version 0.7
[    2.610833] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[    2.610841] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.RP05.PXSX
[    2.610855] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[    2.610863] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[    2.610910] bbswitch: No suitable _DSM call found.
</pre>

I already updated my nvidia driver to version 325 and my linux kernel to version 3.10.7, but the error still occurs. I'm attaching my log files below. Please let me know, if you need additional information. Thank you for your help!

Greetings
Felix

dmesg: http://pastebin.com/0Thn6U02
Xorg.log: http://pastebin.com/kmFcWcXS
bumblebee.conf: http://pastebin.com/XJDmXbFW

**Comment by sznbg** [comment]
Same problem on same Laptop Acer Aspire V5-573g on Kubuntu 14.04.5 HWE Stack enabled with Kernel 4.4.0-98-generic (xenial)

:~$ optirun -vv --debug bash
[  388.438887] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[  388.439332] [INFO]Configured driver: nvidia
[  388.439559] [DEBUG]optirun version 3.2.1 starting...
[  388.439572] [DEBUG]Active configuration:
[  388.439576] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  388.439580] [DEBUG] X display: :8
[  388.439584] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-387:/usr/lib32/nvidia-387
[  388.439588] [DEBUG] Socket path: /var/run/bumblebee.socket
[  388.439593] [DEBUG] Accel/display bridge: auto
[  388.439596] [DEBUG] VGL Compression: proxy
[  388.439600] [DEBUG] VGLrun extra options: 
[  388.439608] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[  388.439724] [DEBUG]Using auto-detected bridge virtualgl
[  388.733801] [INFO]Response: No - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)

[  388.733835] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)

[  388.733847] [DEBUG]Socket closed.
[  388.733889] [ERROR]Aborting because fallback start is disabled.
[  388.733899] [DEBUG]Killing all remaining processes.

Is it the same Error like in the old Kernel 3. xxx ?

In grub.cfg i used the option acpi_osi=Linux acpi_osi=!
But that's none solution. bbswitch: _DSM call ....

Waiting for your reply.
